/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Evena API
 * OpenAPI spec version: 1.0
 */

export type FindEventsParams = {
/**
 * An offset event ID. The result set will contain events after the ID value specified
 */
offset?: string;
/**
 * The size of the resultset
 * @minimum 1
 */
batchSize?: number;
};
