[build]
base = "."
command = "pnpm build"
publish = "dist/evena/browser"
functions = "apps/backend/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/server/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/.netlify/functions/angular-ssr"
status = 200

[context.production]
command = "pnpm build --configuration production"

[context.preview-deploy]
command = "pnpm run build --configuration staging"

[build.environment]
NODE_VERSION = "26.5.0"
PNPM_FLAGS = "--shamefully-hoist"

# [[plugins]]
# package = "@netlify/angular-runtime"
