/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Evena API
 * OpenAPI spec version: 1.0
 */
import type { EventLookupAddress } from './event-lookup-address';
import type { EventLookupType } from './event-lookup-type';

export interface EventLookup {
  id: string;
  name: string;
  /** @nullable */
  description?: string | null;
  lastModified?: string;
  startedAt?: string;
  attendees?: number;
  pendingReservations?: number;
  maxAttendees?: number;
  overflow?: number;
  addressType: string;
  address?: EventLookupAddress;
  tags?: string[];
  /** @nullable */
  attendeeLimit?: number | null;
  type: EventLookupType;
  /** @nullable */
  ticketCost?: number | null;
  currency: string;
}
