name: Backend Deploy
on:
  pull_request:
    paths:
      - apps/backend/**/*.ts
    types:
      - closed
  workflow_dispatch:
  push:
    paths:
      - apps/backend/**/*.ts
    tags:
      - v*.*.*
    branches:
      - master

jobs:
  deploy_backend:
    name: Trigger Render Deployment
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_PROD_HOOK }}
    steps:
      - run: curl -X POST ${{ env.DEPLOY_HOOK }}
